name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Clean and Build with Maven
      run: mvn clean package

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        files: target/ForceElytra-1.0-SNAPSHOT.jar
        body: |
          This is an automatic release created by GitHub Actions.
        draft: false
        prerelease: false
        repository: ${{ github.repository }}
        target_commitish: ${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_unmatched_files: false
