name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package assembly:single --file pom.xml

    - name: Get the latest release
      id: get_latest_release
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/${{ github.repository }}/releases/latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Print latest release URL
      run: echo "The latest release URL is ${{ steps.get_latest_release.outputs.data.url }}"
      
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_latest_release.outputs.data.upload_url }}
        asset_path: ./target/ForceElytra-1.0-SNAPSHOT-jar-with-dependencies.jar
        asset_name: ForceElytra-1.0-SNAPSHOT.jar
        asset_content_type: application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
