name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Clean and Build with Maven
      run: mvn clean package

    - name: Get latest tag
      id: get_tag
      run: |
        echo ::set-output name=tag::$(git describe --tags --abbrev=0)

    - name: Extract version number
      id: extract_version
      run: |
        TAG=${{ steps.get_tag.outputs.tag }}
        VERSION=${TAG#v}
        echo "::set-output name=version::$VERSION"

    - name: Increment version
      id: increment_version
      run: |
        NEXT_VERSION=$(( ${{ steps.extract_version.outputs.version }} + 1 ))
        echo "::set-output name=next_version::$NEXT_VERSION"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release v1.0.${{ steps.increment_version.outputs.next_version }}
        tag_name: v1.0.${{ steps.increment_version.outputs.next_version }}
        files: target/ForceElytra-1.0-SNAPSHOT.jar
        body: |
          This is an automatic release created by GitHub Actions.
        draft: false
        prerelease: false
        repository: ${{ github.repository }}
        target_commitish: ${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_unmatched_files: false
